--------------------
Failed to process https://github.com/sorellabs/fuck-you.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 135, in measure_quality
    (restarts, repository))
RuntimeError: Run out of 3 attempts. Failed to train proper model for https://github.com/sorellabs/fuck-you.git.
--------------------
Failed to process https://github.com/mozilla/pontoon.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 137, in measure_quality
    bblfsh=bblfsh, config_json=config)
  File "/lookout-sdk-ml/lookout/core/helpers/analyzer_context_manager.py", line 87, in review
    log_level=log_level, config_json=config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 101, in review
    return self._run("review", fr, to, port, git_dir, bblfsh, log_level, config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 131, in _run
    return subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/tmp/lookout-sdk-ml/lookout-sdk-v0.7.0', 'review', 'ipv4://localhost:20345', '--from', '4dcc96d33e018602137876ab59e2acf87748c60b', '--to', 'eebb312e4a217adec66dafa94848fb1979260d3f', '--git-dir', '/tmp/top-repos-quality-repos-xxat5ohs/pontoon.git', '--log-format', 'json', '--log-level', 'warning', '--config-json', '{"style.format.analyzer.FormatAnalyzer": {"aggregate": true}}']' returned non-zero exit status 1.
