--------------------
Failed to process https://github.com/babel/example-node-server.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 135, in measure_quality
    (restarts, repository))
RuntimeError: Run out of 3 attempts. Failed to train proper model for https://github.com/babel/example-node-server.git.
--------------------
Failed to process https://github.com/jsfiddle/togetherjs.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 135, in measure_quality
    (restarts, repository))
RuntimeError: Run out of 3 attempts. Failed to train proper model for https://github.com/jsfiddle/togetherjs.git.
--------------------
Failed to process https://github.com/developit/web-worker.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 135, in measure_quality
    (restarts, repository))
RuntimeError: Run out of 3 attempts. Failed to train proper model for https://github.com/developit/web-worker.git.
--------------------
Failed to process https://github.com/mishoo/uglifyjs-old.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 135, in measure_quality
    (restarts, repository))
RuntimeError: Run out of 3 attempts. Failed to train proper model for https://github.com/mishoo/uglifyjs-old.git.
--------------------
Failed to process https://github.com/googlearchive/code-prettify.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 135, in measure_quality
    (restarts, repository))
RuntimeError: Run out of 3 attempts. Failed to train proper model for https://github.com/googlearchive/code-prettify.git.
--------------------
Failed to process https://github.com/parallels/rq-dashboard.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 137, in measure_quality
    bblfsh=bblfsh, config_json=config)
  File "/lookout-sdk-ml/lookout/core/helpers/analyzer_context_manager.py", line 87, in review
    log_level=log_level, config_json=config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 101, in review
    return self._run("review", fr, to, port, git_dir, bblfsh, log_level, config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 131, in _run
    return subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/tmp/lookout-sdk-ml/lookout-sdk-v0.7.0', 'review', 'ipv4://localhost:31562', '--from', '570839ac24772c8c1d7b51a3e402dbf38570af52', '--to', '3a3c91a910f7d82f16421c9dd29f6f1116df710a', '--git-dir', '/tmp/top-repos-quality-repos-zcprqmoy/rq-dashboard.git', '--log-format', 'json', '--log-level', 'warning', '--config-json', '{"style.format.analyzer.FormatAnalyzer": {"aggregate": true}}']' returned non-zero exit status 1.
--------------------
Failed to process https://github.com/monzo/response.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 137, in measure_quality
    bblfsh=bblfsh, config_json=config)
  File "/lookout-sdk-ml/lookout/core/helpers/analyzer_context_manager.py", line 87, in review
    log_level=log_level, config_json=config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 101, in review
    return self._run("review", fr, to, port, git_dir, bblfsh, log_level, config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 131, in _run
    return subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/tmp/lookout-sdk-ml/lookout-sdk-v0.7.0', 'review', 'ipv4://localhost:31562', '--from', '6f617f9e24159e577f7a0c0dc47b6dcbac0c6830', '--to', '0f8d2a8378a02c1f4680a04e4a943d7e32234a22', '--git-dir', '/tmp/top-repos-quality-repos-3e66q4ih/response.git', '--log-format', 'json', '--log-level', 'warning', '--config-json', '{"style.format.analyzer.FormatAnalyzer": {"aggregate": true}}']' returned non-zero exit status 1.
