--------------------
Failed to process https://github.com/acmahjong/acmahjong.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 137, in measure_quality
    bblfsh=bblfsh, config_json=config)
  File "/lookout-sdk-ml/lookout/core/helpers/analyzer_context_manager.py", line 87, in review
    log_level=log_level, config_json=config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 101, in review
    return self._run("review", fr, to, port, git_dir, bblfsh, log_level, config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 131, in _run
    return subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/tmp/lookout-sdk-ml/lookout-sdk-v0.7.0', 'review', 'ipv4://localhost:29445', '--from', 'b40a1ffdf1cd4b620dec9f19a660b35c5aaaf8c7', '--to', 'b40a1ffdf1cd4b620dec9f19a660b35c5aaaf8c7', '--git-dir', '/tmp/top-repos-quality-repos-57k58phw/acmahjong.git', '--log-format', 'json', '--log-level', 'warning', '--config-json', '{"style.format.analyzer.FormatAnalyzer": {"aggregate": true}}']' returned non-zero exit status 1.
--------------------
Failed to process https://github.com/changja88/study_python_clean_code.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 123, in measure_quality
    git_dir = ensure_repo(repository, tmpdirname)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 54, in ensure_repo
    porcelain.clone(repository, git_dir)
  File "/usr/local/lib/python3.6/dist-packages/dulwich/porcelain.py", line 353, in clone
    depth=depth, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dulwich/porcelain.py", line 1121, in fetch
    depth=depth)
  File "/usr/local/lib/python3.6/dist-packages/dulwich/client.py", line 398, in fetch
    progress=progress, depth=depth)
  File "/usr/local/lib/python3.6/dist-packages/dulwich/client.py", line 1644, in fetch_pack
    b"git-upload-pack", url)
  File "/usr/local/lib/python3.6/dist-packages/dulwich/client.py", line 1532, in _discover_references
    resp, read = self._http_request(url, headers, allow_compression=True)
  File "/usr/local/lib/python3.6/dist-packages/dulwich/client.py", line 1510, in _http_request
    (resp.status, url))
dulwich.errors.GitProtocolError: unexpected http resp 401 for https://github.com/changja88/study_python_clean_code.git/info/refs?service=git-upload-pack
--------------------
Failed to process https://github.com/vitaliylevitskiand/wordsplay.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 135, in measure_quality
    (restarts, repository))
RuntimeError: Run out of 3 attempts. Failed to train proper model for https://github.com/vitaliylevitskiand/wordsplay.git.
--------------------
Failed to process https://github.com/borysnie/generatedummyfile.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 137, in measure_quality
    bblfsh=bblfsh, config_json=config)
  File "/lookout-sdk-ml/lookout/core/helpers/analyzer_context_manager.py", line 87, in review
    log_level=log_level, config_json=config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 101, in review
    return self._run("review", fr, to, port, git_dir, bblfsh, log_level, config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 131, in _run
    return subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/tmp/lookout-sdk-ml/lookout-sdk-v0.7.0', 'review', 'ipv4://localhost:29445', '--from', 'd51fc1987b902876ab316eb46f4c5bad900e5427', '--to', 'd51fc1987b902876ab316eb46f4c5bad900e5427', '--git-dir', '/tmp/top-repos-quality-repos-yybao6in/generatedummyfile.git', '--log-format', 'json', '--log-level', 'warning', '--config-json', '{"style.format.analyzer.FormatAnalyzer": {"aggregate": true}}']' returned non-zero exit status 1.
--------------------
Failed to process https://github.com/aharpt/gulp-basic-library.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 137, in measure_quality
    bblfsh=bblfsh, config_json=config)
  File "/lookout-sdk-ml/lookout/core/helpers/analyzer_context_manager.py", line 87, in review
    log_level=log_level, config_json=config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 101, in review
    return self._run("review", fr, to, port, git_dir, bblfsh, log_level, config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 131, in _run
    return subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/tmp/lookout-sdk-ml/lookout-sdk-v0.7.0', 'review', 'ipv4://localhost:29445', '--from', '2a21be97ea8725409f32ad2ee73055f82cd452b1', '--to', '28292676577f356177551c62c61a0575340ae306', '--git-dir', '/tmp/top-repos-quality-repos-j_aazg8x/gulp-basic-library.git', '--log-format', 'json', '--log-level', 'warning', '--config-json', '{"style.format.analyzer.FormatAnalyzer": {"aggregate": true}}']' returned non-zero exit status 1.
